### ISSUE TITLE
Crear modelo de datos

### ISSUE THREAD

**Issue by jjxp** [songs2you/songs2you#1]
Se espera que, en un principio, los datos que se almacenen sean los que se indican a continuación:

* Artista
- Nombre
- Miembros (opcional)
- Géneros
- Álbumes (FK)
- Canciones (FK)

* Álbum
- Nombre
- Fecha de publicación
- Géneros (opcional)
- Imagen de portada
- Artista (FK)
- Canciones (FK)

* Canción
- Nombre
- Enlace YouTube
- Géneros (opcional)
- Artista (FK)
- Álbum (FK)

**Comment by CeuxDruman** [comment]
Me surgen un par de dudas en cuanto al modelo propuesto:
-Cuando te refieres a "Géneros", ¿No deberíamos crear otra tabla "Género"? Creo que sería lo mejor para poder luego realizar búsquedas/agrupaciones/recomendaciones por género.
-En cuanto a la "Imagen de portada" del Álbum, supongo que te referirás el enlace a la misma y no al binario de esta, ¿no?

**Comment by jjxp** [comment]
Respecto a la primera cuestión que planteas, la respuesta corta a ¿no deberíamos crear otra tabla "Género"? sería que sí. La respuesta larga sería que no. En Business Intelligence y cuando se trabaja con grandes volúmenes de datos que además te interesa que estén catalogados "de fábrica", no se suele respetar la tercera forma normal por coherencia de datos y por eficiencia.

En relación a la segunda pregunta, sí, me refiero al enlace de la misma. En el fichero de carga de datos a modo de stub puedes encontrar ejemplos de datos por si surge alguna otra duda.

**Comment by CeuxDruman** [comment]
Tras analizar las distintas posibilidades en #2 , el modelo de datos resultante debería ser el siguiente:

## Artist
Name
Members
Genre
Styles
Photo [URL]

## Album
Name
ReleaseDate
Genre
Styles
CoverImage [URL]
Label
Duration [HH:mm]
Artist (FK)

## Song
Name
Genre
Styles
Duration [mm:SS]
Composers
Album (FK)

**Comment by CeuxDruman** [comment]
Durante el scrapping, me he percatado de que cada Artista, Álbum y Canción tiene su propio identificador visible dentro de la web que, además, ayuda a realizar cualquier "búsqueda" posterior mediante sencillas URLs y ayudaría en un futuro si cambiasen las URLs de acceso de la plataforma. Por lo que en vez de utilizar el clásico identificador numérico ascendente para las tablas y almacenar las URLs de los artistas para sacar su biografía a posteriori, haremos uso de estos identificadores únicos.

**Comment by CeuxDruman** [comment]
Tras detectar la utilidad del número de pista como dato de las canciones y ser comentada y aprobada con los distintos miembros del grupo, la añadimos al modelo de datos.

Además, hemos eliminado el campo compositores como dato de las canciones debido a que no aporta nada fundamental para nuestra aplicación.

Por lo tanto, el modelo de datos resultante es el siguiente:

## Artist
Name
Members
Genre
Styles
Photo [URL]

## Album
Name
ReleaseDate
Genre
Styles
CoverImage [URL]
Label
Duration [HH:mm]
Artist (FK)

## Song
TrackNumber
Name
Genre
Styles
Duration [mm:SS]
Album (FK)
