### ISSUE TITLE
Generar dataset

### ISSUE THREAD

**Issue by jjxp** [songs2you/songs2you#2]
Se debe generar un dataset que contenga la información que se requiere en el modelo (para más información, ver #1).

Con un número pequeño de artistas debería ser suficiente (quizás entre 300 y 500). Si no se puede obtener de forma sencilla un conjunto de artistas que satisfaga estas necesidades, se podría optar por:
* Introducir los nombres a mano (el número de artistas sería mucho más reducido y poco variado).
* Tomar los 300-500 artistas más escuchados del dataset de last.fm

Una vez se tenga una lista con los nombres de los artistas, se podría hacer scrapping de Google. Ejemplo: 
![image](https://cloud.githubusercontent.com/assets/9135377/21567176/4a0dd6b6-ceaa-11e6-89a4-78cb5aecff5d.png)
![image](https://cloud.githubusercontent.com/assets/9135377/21567184/5404b306-ceaa-11e6-85a8-32726726a0bb.png)

Del mismo modo se procedería con el resto de entidades del modelo que son necesarias.

**Comment by CeuxDruman** [comment]
¿Os parece bien el formato .csv (semicollons separated) para el dataset generado? Para que se tenga en cuenta en la realización del Issue #3 .

Creo que es mejor que "comma separated", ya que hay ciertas canciones o álbumes que pueden incluir comas, como se puede ver en las imágenes de ejemplo que expone @jjxp .

**Comment by jjxp** [comment]
Perfecto. Sería incluso recomendable trabajar con formato .csv, que además permite:

- Ser abierto con otros programas (MS Excel)
- Leerlo con un paquete nativo de Python (paquete _csv_)
- Añadir delimitadores tanto a campos como a contenido, de tal forma que se solucionaría el problema de que cierto atributo contuviera el limitador que se esté utilizando (semicolon _;_ por defecto)

**Comment by CeuxDruman** [comment]
Dada la dificultad de realizar scrapping sobre Google debido a la limitación de peticiones que permite y el riesgo de banneo de IP permanente, propongo la siguiente web, así como los datos que podríamos o no obtener de ella según el modelo propuesto en #1 :

_Leyenda:_
- [x] _Dato disponible en la web_
- [ ] _Dato no disponible en la web_
- [x] _**Dato adicional disponible en la web**_

## [LetSingIt](http://www.letssingit.com/) : Concretamente su sección de "[Artistas](http://www.letssingit.com/browse/a/1)".

**Artista**
- [x] Nombre
- [ ] Miembros (opcional)
- [x] Géneros
- [x] **Fotos**
- [x] **Biografía**

**Álbum**
- [x] Nombre
- [x] Fecha de publicación
- [x] Géneros (opcional)
- [ ] Imagen de portada*
- [x] **Discográfica**

**Canción**
- [x] Nombre
- [x] Enlace YouTube
- [x] Géneros (opcional)
- [x] **Letra**
- [x] **Autor de la letra**

Además, tanto artistas como sus discos y cada canción individualmente, poseen puntuaciones de 0.0 a 5.0 hechas por los usuarios de la web, que podríamos tomar como base de puntuaciones para sistemas de recomendación.

*La imagen de portada "oficial" no puede obtenerse, pero sí el thumbnail del vídeo de Youtube. (se encuentra en el mismo código de la página, no hay que acceder al vídeo de youtube ni otros medios)

Ejemplos de imagenes resultantes a partir del vídeo de youtube insertado en LetSingIt:
![image](https://cloud.githubusercontent.com/assets/11983593/21650404/237e2010-d2a5-11e6-8d4f-bac85724c6f6.png)
![image](https://cloud.githubusercontent.com/assets/11983593/21650462/56413172-d2a5-11e6-8307-c78758dcdde9.png)

Quedo a la espera de que me comentéis si os parece bien esta web como foco del scrapping y qué datos adicionales creéis convenientes añadir, si procede.

**Comment by jjxp** [comment]
Enumero un conjunto de puntos que creo conveniente comentar sobre tu propuesta:

* No veo ningún problema en incluir atributos como fotos de los artistas. Sería, incluso, conveniente. Sin embargo, no guardaría la biografía de estos. Tampoco guardaría, en el caso de las canciones, la letra y el autor de la letra de cada una. Estos datos harían crecer el dataset en tamaño y "ensuciaría" la base de datos con datos que se pueden obtener en tiempo de ejecución. Dicho de otra forma, en vez de guardar información que sólo se va a mostrar en muy contadas ocasiones (de entre todas las posibilidades que hay), ¿no es más sencillo obtener la información de otra web cuando el usuario la pida?
* En cuanto a la imagen de portada de los álbumes, buscaría otra alternativa. Hay vídeos en los que el thumbnail de YouTube no coincide con la portada del álbum. Conociendo el nombre del álbum, se podría obtener esta información de otra web sin problemas.
* Las puntuaciones no las guardaría. Según he estado mirando, el conjunto de puntuaciones es muy pobre (como máximo he visto 5 votaciones para una canción) y 1. son demasiado pocas para un sistema de recomendación; y 2. nuestro sistema de recomendación es basado en contenido, no en usuarios. Para ser basado en usuario como propones necesitaríamos cientos de miles de valoraciones.
* Si no hay otra web de la que hacer scrapping, no vería problema en utilizar esta (teniendo en cuenta las consideraciones descritas en los puntos anteriores). Sin embargo, la calidad de los datos es bastante pobre. Hay muchos datos incompletos o que no son correctos. Adjunto ejemplo:
![image](https://cloud.githubusercontent.com/assets/9135377/21651876/a71e03fe-d2aa-11e6-9c5f-46c18b475f4a.png)
De todos los anteriores, sólo el primero y los tres últimos son realmente álbumes. El resto son singles que no deberían ser considerados como tal.

**Comment by CeuxDruman** [comment]
Otra alternativa con una fiabilidad de datos bastante más buena:

## [AllMusic.com](http://www.allmusic.com/)
El principal problema de esta alternativa es que para obtener el listado completo de sus canciones (y por lo tanto álbumes y artistas) hay que realizar una búsqueda dinámica y las herramientas vistas en la asignatura no permiten el análisis dinámico de páginas web. Sin embargo, navegando por sus distintas secciones, he encontrado un método por el cuál obtener 720 artistas (no repetidos) con todos sus álbumes y canciones.

Todos los artistas y álbumes poseen fotos (en el caso de los álbumes la portada oficial), sin embargo la principal desventaja es que las canciones no tienen enlace a YouTube.

**Artista**
- [x] Nombre
- [x] Miembros (opcional)
- [x] Géneros
- [x] **Estilos**
- [x] **Fotos**
- [x] **Biografía**

**Álbum**
- [x] Nombre
- [x] Fecha de publicación
- [x] Géneros (opcional)
- [x] Imagen de portada*
- [x] **Estilos**
- [x] **Discográfica**
- [x] **Duración**

**Canción**
- [x] Nombre
- [ ] Enlace YouTube
- [x] Géneros (opcional)
- [x] **Estilos**
- [x] **Duración**
- [x] **Compositor**

Además, dispone también de puntuaciones, tanto por parte de "AllMusic" como de los usuarios en el caso de los álbumes (desde decenas hasta cientos de votos según la popularidad del álbum), como sólo de "AllMusic" en el caso de las Canciones.

De nuevo, cuento con vuestra colaboración para valorar el uso de esta web como base del scrapping así como la inclusión o no de los distintos datos adicionales que ésta aporta.

**Comment by CeuxDruman** [comment]
**Actualizo**: Tras analizar aún más a fondo la web, va a ser posible obtener un total de:
- 21 Géneros
- 48 Artistas por género (En casi todos los casos)

Es decir, aproximadamente **1000 Artistas** con sus distintos álbumes y canciones.
